name: Run Tests
on:
  push:
  pull_request:
jobs:
  tweet:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "pnpm"
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Typecheck Code
        run: pnpm tsc --noEmit
      - name: Run Tests
        run: pnpm test
